### PR TITLE
Ji 89 add servingtime functionality

### PR DESCRIPTION
**Pull request by palleBrandt**

### CODE REVIEW

**Review by OmarSemou — CHANGES_REQUESTED** [review]
It looks great but the test for serving time controller is failing. Looks like some compilation error

**Comment by OmarSemou** [comment]
Flutter test is still failing unfortunately :( 

❌ loading /home/runner/work/JunkFoodApp/JunkFoodApp/test/servingtime_controller_test.dart (failed)

**Comment by palleBrandt** [comment]
> Flutter test is still failing unfortunately :(
> 
> ❌ loading /home/runner/work/JunkFoodApp/JunkFoodApp/test/servingtime_controller_test.dart (failed)

Problem with testing should be resolved now.

**Review by JKramer91 — APPROVED** [review]

**Review by OmarSemou — APPROVED** [review]
Love the quick fix, awesome job!

**Pull request merged**
